version: 3
jobs:
  build:
    docker:
      - image: rocker/verse:4.1.2
    environment:
            _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update -y && sudo apt-get install tk zip libcurl4-openssl-dev libssl-dev libxml2-dev libgmp-dev libglpk-dev -y  
      - run: 
          name: Install matrixStats
          command: R -e "install.packages('https://cran.r-project.org/src/contrib/matrixStats_1.2.0.tar.gz', repos=NULL, type='source')"
      - run: 
          name: Install DESeq2, SummarizedExperiment
          command:  R -e "BiocManager::install(c('DESeq2', 'SummarizedExperiment'), ask = FALSE, update = TRUE)"       
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)" 
      - run: 
          name: Install sccore v1.0.4
          command: R -e "install.packages('pbmcapply')" \
                   R -e "install.packages('https://cran.r-project.org/src/contrib/sccore_1.0.4.tar.gz', repos=NULL, type='source')" \
      - run: 
          name: Install igraph v1.6.0
          command: R -e "install.packages('https://cran.r-project.org/src/contrib/igraph_1.6.0.tar.gz', repos=NULL, type='source')"   
      - run: 
          name: Install leidenAlg v1.1.2
          command: R -e "install.packages('https://cran.r-project.org/src/contrib/leidenAlg_1.1.2.tar.gz', repos=NULL, type='source')"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --no-manual *tar.gz 
      - store_test_results:
          path: tmp/tests
