# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkBits <- function() {
    .Call('_conos_checkBits', PACKAGE = 'conos')
}

checkOpenMP <- function() {
    .Call('_conos_checkOpenMP', PACKAGE = 'conos')
}

findBestClusterThreshold <- function(merges, clusters, clusterTotals) {
    .Call('_conos_findBestClusterThreshold', PACKAGE = 'conos', merges, clusters, clusterTotals)
}

cpcaF <- function(cov, ng, ncomp = 10L, maxit = 1000L, tol = 1e-6, eigenvR = NULL, verbose = TRUE) {
    .Call('_conos_cpcaF', PACKAGE = 'conos', cov, ng, ncomp, maxit, tol, eigenvR, verbose)
}

greedyModularityCut <- function(merges, deltaM, N, minsize = 0L) {
    .Call('_conos_greedyModularityCut', PACKAGE = 'conos', merges, deltaM, N, minsize)
}

referenceWij <- function(i, j, d, threads, perplexity) {
    .Call('_conos_referenceWij', PACKAGE = 'conos', i, j, d, threads, perplexity)
}

sgd <- function(coords, targets_i, sources_j, ps, weights, gamma, rho, n_samples, M, alpha, momentum, useDegree, seed, threads, verbose) {
    .Call('_conos_sgd', PACKAGE = 'conos', coords, targets_i, sources_j, ps, weights, gamma, rho, n_samples, M, alpha, momentum, useDegree, seed, threads, verbose)
}

n2Knn <- function(m, k, nThreads = 10L, verbose = TRUE, indexType = "angular", M = 12L, MaxM0 = 24L) {
    .Call('_conos_n2Knn', PACKAGE = 'conos', m, k, nThreads, verbose, indexType, M, MaxM0)
}

n2CrossKnn <- function(mA, mB, k, nThreads = 10L, verbose = TRUE, indexType = "angular", M = 12L, MaxM0 = 24L) {
    .Call('_conos_n2CrossKnn', PACKAGE = 'conos', mA, mB, k, nThreads, verbose, indexType, M, MaxM0)
}

propagate_labels <- function(edge_verts, edge_weights, vert_labels, max_n_iters = 10L, verbose = TRUE) {
    .Call('_conos_propagate_labels', PACKAGE = 'conos', edge_verts, edge_weights, vert_labels, max_n_iters, verbose)
}

smooth_count_matrix <- function(edge_verts, edge_weights, count_matrix, max_n_iters = 10L, diffusion_fading = 1.0, diffusion_fading_const = 0.1, tol = 1e-3, verbose = TRUE) {
    .Call('_conos_smooth_count_matrix', PACKAGE = 'conos', edge_verts, edge_weights, count_matrix, max_n_iters, diffusion_fading, diffusion_fading_const, tol, verbose)
}

adjacent_vertices <- function(edge_verts) {
    .Call('_conos_adjacent_vertices', PACKAGE = 'conos', edge_verts)
}

adjacent_vertex_weights <- function(edge_verts, edge_weights) {
    .Call('_conos_adjacent_vertex_weights', PACKAGE = 'conos', edge_verts, edge_weights)
}

spcov <- function(m, cm) {
    .Call('_conos_spcov', PACKAGE = 'conos', m, cm)
}

