# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interNN <- function(mA, mB, kA, kB, spaceType = 2L, lpSpaceP = 2.0, verbose = TRUE, neighbourhoodAverage = TRUE, neighbourAvgKA = 10L, neighbourAvgKB = 10L, mutualOnly = TRUE) {
    .Call('_clusterMatch_interNN', PACKAGE = 'clusterMatch', mA, mB, kA, kB, spaceType, lpSpaceP, verbose, neighbourhoodAverage, neighbourAvgKA, neighbourAvgKB, mutualOnly)
}

neighbourhoodAverageMatrix <- function(mA, verbose = TRUE, lpSpaceP = 2.0, spaceType = 2L, nThreads = 30L, k = 10L) {
    .Call('_clusterMatch_neighbourhoodAverageMatrix', PACKAGE = 'clusterMatch', mA, verbose, lpSpaceP, spaceType, nThreads, k)
}

neighbourhoodAverageMatrix2 <- function(mA, verbose = TRUE, lpSpaceP = 2.0, spaceType = 2L, nThreads = 30L, k = 10L) {
    .Call('_clusterMatch_neighbourhoodAverageMatrix2', PACKAGE = 'clusterMatch', mA, verbose, lpSpaceP, spaceType, nThreads, k)
}

